language: python
addons:
  ssh_known_hosts: chtoes.li
python:
- '2.7'
install:
- pip install -r requirements.txt
script: fab build
before_install:
- openssl aes-256-cbc -K $encrypted_1695f9421a83_key -iv $encrypted_1695f9421a83_iv -in deploy_key.enc -out deploy_key -d -in deploy_key.enc -out deploy_key -d
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/deploy_key
- ssh-add $TRAVIS_BUILD_DIR/deploy_key
- fab publish:ci
