language: python
addons:
  ssh_known_hosts: chtoes.li
python:
- '3.5'
install:
- pip install -r requirements.txt
script:
- fab build:ci
- flake8 md_extensions/*.py
before_install:
- openssl aes-256-cbc -K $encrypted_3829a9af3a1a_key -iv $encrypted_3829a9af3a1a_iv
  -in ci.chtoes.li.enc -out deploy_key -d
after_success:
- bash deploy.sh
