language: python
addons:
  ssh_known_hosts: chtoes.li
python:
- '2.7'
- '3.5'
install:
- pip install -r requirements.txt
script:
- fab build:ci
- flake8 md_extensions/*.py
before_install:
- openssl aes-256-cbc -K $encrypted_1695f9421a83_key -iv $encrypted_1695f9421a83_iv -in deploy_key.enc -out deploy_key -d -in deploy_key.enc -out deploy_key -d
after_success:
- bash deploy.sh
